name: Deploy Cognite Function
on:
  push:
    branches:
    - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: cognitedata/function-action@v2
      with:
          function_name: my_hello_function_${{ github.ref }}
          cdf_deployment_credentials: ${{ secrets.COGNITE_FUNCTION_CREDENTIALS }}
          cdf_runtime_credentials: ${{ secrets.COGNITE_FUNCTION_CREDENTIALS }}
          function_file: handler.py
          common_folder: folder1
          function_folder: folder2
    